Repository Team138Entropy/Entropy2020, pull requests merged in 2020-02, with the labels that each got.

#67 Add driver cameras
  readme.md
  src/main/deploy/config.properties
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/subsystems/CameraManager.java
Labels: enhancement, help wanted

#77 Add speed lookup table (still needs real data)
  src/main/java/frc/robot/SpeedLookupTable.java
  src/main/java/frc/robot/subsystems/Shooter.java
Labels: enhancement

#82 Display current state in shuffleboard
  src/main/java/frc/robot/Robot.java
Labels: enhancement

#89 Add hardcore gitignore
  .gitignore
Labels: enhancement

#102 Intake overcurrent fixes
  shuffleboard/main.json
  src/main/deploy/config.properties
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/subsystems/Shooter.java
  src/main/java/frc/robot/subsystems/Storage.java
  src/main/java/frc/robot/subsystems/VisionManager.java
Labels: enhancement

#106 Camera tuning
  EVBallFinder.py
  EVHighGoalFinder.py
Labels: enhancement, fundamental

#136 Add automatic system test
  shuffleboard/main.json
  src/main/deploy/config.properties
  src/main/java/frc/robot/Config.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/subsystems/CameraManager.java
  src/main/java/frc/robot/subsystems/Drive.java
Labels: enhancement

#145 Vision toggle
  src/main/java/frc/robot/OI/OperatorInterface.java
  src/main/java/frc/robot/Robot.java
Labels: enhancement
